---
title: "Methodology"
output: html_document
---

The code behind this app as well as an excel file with links to all team logos can be found at my [GitHub](https://github.com/DSchof1/CBB-Stats). 

&nbsp;

<h4>Where does the data come from?</h4>

All data used in this app I either collected myself (logos) or was scraped from [Bart Torvik](https://barttorvik.com/#).   

&nbsp;

&nbsp;

<h4>Why do the scores have decimals?</h4>


<div style="text-align:justify;"> Scores have decimals to be precise.  Two teams very close in skill level may result in a final score that is only separated by less than a point.  But no game can end in a tie, so it's important to know how much more favoured a certain team is.  Furthermore in the sports betting world the margin of games is very important, therefore we want to also know what the exact expected margin of victory is, and not a rounded approximation.  </div>

&nbsp;

&nbsp;

<h4>What does the NCAA logo represent?</h4>

The logo is used to represent how a team would fare against the average NCAA Division 1 team.  

&nbsp;

&nbsp;

<h4>How does the matchup predictor work?</h4>

I will attempt to simplify alot of it here, but [Bart Torvik](http://adamcwisports.blogspot.com/p/every-possession-counts.html) and [KenPom](https://kenpom.com/blog/ratings-methodology-update/
) go into much more detail if you are curious.  

 The chance a team has to beat another team is predicated on the [Log5 methodology](https://web.williams.edu/Mathematics/sjmiller/public_html/399/handouts/Log5WonLoss_Paper.pdf) first developed in 1981 by Bill James, creator of the famous [sabermetrics](https://en.wikipedia.org/wiki/Sabermetrics).  The Log5 method has the following the equation for the probability of team A defeating team B:

&nbsp;

<div align="center"> $$p_{A,B} = \frac{p_A-(p_A \cdot p_B)}{p_A + p_B - 2(p_A \cdot p_B)}$$ </div>

&nbsp;

For college basketball the variables $p_A$ and $p_B$ represent:

* $p_A =$ The probability team A defeats the average NCAA Division 1 team
* $p_B =$ The probability team B defeats the average NCAA Division 1 team

&nbsp;

&nbsp;

<h4>How are these probabilities calculated?</h4>

<div style="text-align:justify;"> In order to calculate these probabilities we need two things, Adjusted Offensive Efficiency and Adjusted Defensive Efficiency.  Each of these is calculated on a per-game basis and averaged to get the overall values.  The per-game numbers for one team are calculated as follows: </div>

&nbsp;

<div align="center"> $$OE_{GA} = \frac{PPP_O}{\frac{OAdjDE}{PPP_A}}$$ </div>

&nbsp;

<div align="center">$$DE_{GA} = \frac{PPP_D}{\frac{OAdjOE}{PPP_A}}$$ </div>

Where:

* $OE_{GA} =$ Game Adjusted Offensive Efficiency
* $DE_{GA} =$ Game Adjusted Defensive Efficiency
* $PPP_O =$ Points Scored Per Possession on Offense
* $PPP_D =$ Points Allowed Per Possession on Defense
* $PPP_A =$ NCAA Average Points Per Possession
* $OAdjOE =$ Opponents Adjusted Offensive Efficiency
* $OAdjDE =$ Opponents Adjusted Defensive Efficiency

&nbsp;

Then for each team you average their game scores for Adjusted Offensive and Defensive Efficiency and get their overall adjusted efficiencies.  These adjusted efficiencies are now plugged into Bill James' [Pythagorean Expectation](https://web.williams.edu/Mathematics/sjmiller/public_html/399/handouts/PythagWonLoss_Paper.pdf) formula to calculate what a team's chance of winning would be against the average Division 1 team.  For college basketball the formula is simplified to: 

&nbsp;

<div align="center"> $$ \text{Win Ratio} = \frac{1}{1+(\frac{AdjDE}{AdjOE})^{11.5}}$$ </div>

&nbsp;

Where:

* $AdjDE =$ Adjusted Defensive Efficiency
* $AdjOE =$ Adjusted Offensive Efficiency

*Note: From a predicitive point of view the exponent 11.5 was independently found to be the best by both KenPom and Bart Torvik.  KenPom has since changed this to account for other factors, but Bart Torvik (currently the only data source for this app) has not.*

&nbsp;

Now that we have the probability that a team will defeat the average NCAA Division 1 team we can simply use the Log5 formula above to find the probability that team A will defeat team B.  

&nbsp;

&nbsp;

<h4>How are the game scores calculated?</h4>

Game scores rely on Adjusted Offensive and Defensive Efficiencies as well as Adjusted Tempo.  Tempo is a metric that indicates how fast a team plays.  Simply put, adjusted Tempo is a measurement of how many possessions a team would have against the average Division 1 team.  I won't get into the specifics of how possessions and tempo are calculated, but more info about [possessions](https://cbbstatshelp.com/efficiency/possessions/) and [tempo](https://cbbstatshelp.com/efficiency/tempo-and-pace/) can be found at [College Basketball Stats Help](https://cbbstatshelp.com/).  In order to calculate game score we must first find the expected tempo team A and team B will have compared to the Division 1 average when they play each other.  This is calculated by the following:

&nbsp;

<div align="center"> $$E(Tempo_{A,B}) = \frac{AdjT_A}{AdjT_{NCAA}} \cdot \frac{AdjT_B}{AdjT_{NCAA}} \cdot AdjT_{NCAA}$$ </div>

&nbsp;

Where:

* $E(Tempo_{A,B}) =$ The expected number of possessions that team and A and B will each have
* $AdjT_A =$ The adjusted number of possessions team A has in a game
* $AdjT_B =$ The adjusted number of possessions team B has in a game
* $AdjT_{NCAA} =$ The adjusted number of possessions the average NCAA Division 1 team has in a game

*Note: It is interesting that this formula effectively states that when two teams who have higher than average possessions per game play each other their expected possessions per game are higher than either of their individual possessions per game.*

&nbsp;

Now that we have the expected number of possessions team A and B will each have when they play each other we use the following formulas to calculate the expected number of points A's offense will score against B's defense and vice versa:

&nbsp;

<div align="center"> $$E(Points_A) = AdjOE_A \cdot \frac{AdjDE_B}{AdjDE_{NCAA}} \cdot \frac{E(Tempo_{A,B})}{100} \hspace{1px}$$ 

&nbsp;

$$\hspace{1px} E(Points_B) = AdjOE_B \cdot \frac{AdjDE_A}{AdjDE_{NCAA}} \cdot \frac{E(Tempo_{A,B})}{100}$$ </div>

&nbsp;

Where:

* $AdjOE_A =$ Adjusted Offensive Efficiency of team A
* $AdjDE_A =$ Adjusted Defensive Efficiency of team A
* $AdjOE_B =$ Adjusted Offensive Efficiency of team B
* $AdjDE_B =$ Adjusted Defensive Efficiency of team B
* $AdjDE_{NCAA} =$ Adjusted Defensive Efficiency of the average NCAA Division 1 team
* $E(Tempo_{A,B}) =$ The expected number of possessions that team and A and B will each have

*Note:* $E(Tempo_{A,B})$ *is divided by 100 because tempo is generally expressed as points per 100 possessions, therefore we divide by 100 to find points per single possession.*

&nbsp;

&nbsp;

<h4>What about home-court advantage?</h4>

<div style="text-align:justify;"> Home-court advantage surely does exist and KenPom has a great <a href="https://kenpom.com/blog/mining-point-spread-data-home-court-advantage/">article</a> on it if you want to read more about the numbers behind it.  For many years both Bart Torvik and KenPom used a multiplier of 1.4% for this advantage.  This multiplier was applied to both the home and away teams' Adjusted Offensive and Defensive Efficiencies.  The home team would receive a benefit of 1.4% so their Adjusted Offensive Efficiency would be multiplied by 1.4% and their Adjusted Defensive Efficiency would be multiplied by 98.6% (100% - 1.4%) (since a lower Adjusted Defensive Efficiency is better).  The reverse is true for the visiting team, their Adjusted Offensive Efficiency would be multiplied by 98.6% (100% - 1.4%) and their Adjusted Defensive Efficiency would be multiplied by 1.4%. </div>

&nbsp;

&nbsp;

<h4>How does this multiplier affect the probability a team wins a game and that game's score?</h4>

<div style="text-align:justify;"> If we go back to the Log5 formula we saw that the expected winning percentage of a team was based on the Adjusted Offensive and Defensive Efficiencies of that team.  Hence we are altering the team's odds of beating the average Division 1 team depending on whether they are home or away.  We also saw that the calculation for the expected number of points a team will score relies on the interaction between that team's offense and the opposing team's defense.  As such the multiplier will give a slight buff to the home team's number of points and will give a slight nerf to the away team's number of points. </div>

&nbsp;

&nbsp;

<h4>Is your multiplier 1.4%?</h4>

<div style="text-align:justify;"> In short no.  This season teams either have no fans in attendance or a very limited number.  Fans surely have an impact on the multiplier for home-court advantage.  Therefore without them the multiplier has to be lower.  This is why I have set my multiplier to 1%.  While I determined this empirically I believe it to be a "good enough" approximation for this year when there are such differences due to COVID. </div>

&nbsp;

&nbsp;

<h4>What is coming next?</h4>

<div style="text-align:justify;"> I have plans to expand the matchup predictor to display "Today's Games" with the win probabilities and expected scores.  I may also include betting odds as I know some people are very interested in that.  I also have plans for conference and tournament brackets that allow you to fill them out with "weighted randomness".  Finally, I have plans to build a regression model to predict number of wins and see how it progresses over a season, but it's still in development and probably won't be seen until at the earliest next season. </div>

&nbsp;

&nbsp;
